[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "proto-example"
version = "1.0.0"
description = ""
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
]
license = { text = "Apache License (2.0)" }
dependencies = [
    "flwr[simulation]>=1.9.0,<2.0",
    "flwr-datasets[vision]>=0.0.2,<1.0.0",
    "torch==2.2.1",
    "torchvision==0.17.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[flower]
publisher = "flowerteam"

[flower.components]
serverapp = "proto_example.server:app"
clientapp = "proto_example.client:app"

[flower.engine]
name = "simulation"

[flower.engine.simulation.supernode]
num = 2
