[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "app-pytorch"
version = "1.0.0"
description = ""
authors = [
    { name = "dummy", email = "dummy@dummy.com" },
]
license = {text = "Apache License (2.0)"}
dependencies = [
    "flwr[simulation]>=1.8.0,<2.0",
    "flwr-datasets[vision]>=0.0.2,<1.0.0",
    "torch==2.2.1",
    "torchvision==0.17.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[flower]
publisher = "dummy"

[flower.components]
serverapp = "server:app"
clientapp = "client:app"