name: flwr-containers-e2e-test

services:
  # create a SuperLink service
  superlink:
    image: docker.io/flwr/superlink:nightly
    ports:
      - "9091:9091"
      - "9092:9092"
    command: [ "--insecure" ]